services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKlee\Oelib\:
    resource: '../Classes/*'
    exclude: '../Classes/Configuration/*,../Classes/DataStructures/*,../Classes/Domain/Model/*,../Classes/Interfaces/Configuration.php,../Classes/Model/*'

  OliverKlee\Oelib\Configuration\ConfigurationRegistry:
    public: true

  OliverKlee\Oelib\Email\SystemEmailBuilder:
    public: true

  OliverKlee\Oelib\Mapper\MapperRegistry:
    public: true

  OliverKlee\Oelib\Templating\TemplateRegistry:
    public: true

  OliverKlee\Oelib\Testing\TestingFramework:
    public: true
    shared: false
